server:
    baseUri: http://0.0.0.0:8092/radar-gateway/

kafka:
    producer:
        bootstrap.servers: kafka-1:9092
    serialization:
        schema.registry.url: http://schema-registry-1:8081

auth:
    managementPortalUrl: http://managementportal-app:8080
